### ISSUE TITLE
Class `kigkonsult\iCalcreator\vcalendar` not found

### ISSUE THREAD

**Issue by xchs** [Craffft/contao-calendar-ical-bundle#10]
**Affected version(s)**

`craffft/contao-calendar-ical-bundle` 4.0.6
Contao 4.7.*
PHP 7.3.3

**Description**  

After the `kigkonsult/icalcreator` package has been updated to version `2.27.17` yesterday, I get the following error messages when it comes to generate the ICS file(s):

```
ErrorException: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "vcalendar" from namespace "kigkonsult\iCalcreator".
Did you forget a "use" statement for another namespace? in /var/www/vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php:136
Stack trace:
#0 /var/www/vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(76): Contao\CalendarExport->getAllEvents(Array, 1554481739, 1586017739, '...', '...', '...', '...')
#1 /var/www/vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(58): Contao\CalendarExport->generateFiles(Array)
#2 /var/www/vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(42): Contao\CalendarExport->gen
#1 vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(136): handleFatalError
#0 vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): null
```

```
Error: Class 'kigkonsult\iCalcreator\vcalendar' not found
#18 vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(136): getAllEvents
#17 vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(76): generateFiles
#16 vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(58): generateSubscriptions
#15 vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarExport.php(42): exportCalendar
#14 var/cache/prod/contao/dca/tl_calendar.php(758): generate_ical
#13 vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php(203): __construct
#12 vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php(393): getBackendModule
#11 vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php(163): run
#10 vendor/contao/core-bundle/src/Controller/BackendController.php(48): mainAction
#9 vendor/symfony/http-kernel/HttpKernel.php(149): handleRaw
#8 vendor/symfony/http-kernel/HttpKernel.php(66): handle
#7 vendor/symfony/http-kernel/Kernel.php(188): handle
#6 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): handle
#5 vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): forward
#4 vendor/symfony/framework-bundle/HttpCache/HttpCache.php(57): forward
#3 vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): pass
#2 vendor/symfony/http-kernel/HttpCache/HttpCache.php(183): handle
#1 vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): handle
#0 web/app.php(58): null
```

**Comment by rainermueller** [comment]
Is the issue related to [https://github.com/iCalcreator/iCalcreator/issues/70](https://github.com/iCalcreator/iCalcreator/issues/70)?

**Comment by mv-itb** [comment]
I'm struggeling with the same issue. 
I'm using Contao 4.4.40, Calendar iCal Bundle 4.0.6 with kigkonsult/icalcreator version 2.27.16.
Is an update/fix planned?

**Comment by loilo** [comment]
As this is indeed related to iCalcreator/iCalcreator#70, this can temporarily be solved by adding `"kigkonsult/icalcreator": ">= 2.27"` to a project's [`composer.json` conflicts](https://getcomposer.org/doc/04-schema.md#conflict).

**Comment by mv-itb** [comment]
@loilo Thx a lot! Problem solved. 👍

**Comment by iCodr8** [comment]
@loilo can you add the conflict entry as a pull request?

**Comment by loilo** [comment]
It would be easier to adjust to the new class names, wouldn't it? :)

**Comment by iCodr8** [comment]
Ok, when it solves the problem, can you please change that in a pull request?

**Comment by loilo** [comment]
Sure thing. 👍
